- {{ cookiecutter.repo_name }}/.gitignore
Small edit. Found these in another gitignore.
Should we also ignore .tiff etc? The user could still explicitly add them.
```
#Binary data files
*.volume
*.am
*.tiff
*.tif
*.dat
*.DAT
```
> some editor files

- docs/source/further-reading.rst
Perusing the SciPy tutorials, I found teaching materials that seem to have a
goal similar to this one. It's more like an outline for in-person instruction,
not something that a user could follow on their own, but still useful to link to.
> DOC: Add a link to a related tutorial.

- docs/source/ci.rst
- docs/source/preliminaries.rst
I created a new GitHub account and went through the Travis-CI instructions to
be sure that they would work for a normal new user without a pre-existing
Travis-CI account or any pre-existing settings or integrations.
Fortunately, the instructions were correct, but I have made them a little more
specific about exactly what a new user sees.
> DOC: Make Travis-CI integration instructions more specific.

- docs/source/conf.py
- requirements.txt
- {{ cookiecutter.repo_name }}/docs/source/conf.py
- {{ cookiecutter.repo_name }}/requirements-dev.txt
This adds a copy-to-clipboard button to every code-block.
See https://github.com/choldgraf/sphinx-copybutton
Thanks @choldgraf! :-D
> ENH: Add sphinx-copybutton extension to docs in and about cookiecutter.

- .travis.yml
- README.md
- docs/source/conf.py
- docs/source/index.rst
- docs/source/preliminaries.rst
I originally called this "packaging scientific Python," employing a loose usage
of the word "packaging" that I now think is too confusing. Let's reserve
"packaging" for its technical meaning.
> MNT: Rename project.

- requirements.txt
Surprisingly, the tests run on Travis-CI without this. I suppose that
Travis must include pytest in its testing venv by default.
> FIX: Add pytest to outer requirements.txt.

- {{ cookiecutter.repo_name }}/setup.py
I noticed that this was generated in [setup.py](https://github.com/mrakitin/srwpy/blob/3bd395ff4c1bf07f1c7e08318896452654da10e5/setup.py#L10-L22):
```py
if sys.version_info < (3, 6):
error = """
srwpy does not support Python {0}.{2}.
Python 3.6 and above is required. Check your Python version like so:
python3 --version
This may be due to an out-of-date pip. Make sure you have pip >= 9.0.1.
Upgrade pip like so:
pip install --upgrade pip
""".format(3, 6)
```
However, we don't have the third argument to unpack (for `.{2}`), hence the PR.
> ENH: fix version error in setup.py

- docs/source/refraction.py
- docs/source/test_examples.py
- docs/source/the-code-itself.rst
- docs/source/writing-docs.rst
It was requested by a user that we could simplify the example by using radians instead of degrees, and removing the np.deg2rad(...) calls.
This PR addresses that issue
> modifying the example to use radians instead of degrees

- {{ cookiecutter.repo_name }}/.codecov.yml
THis configuration file lets codecov weigh in on the "checks"
shown by GitHub but suppresses the giant comment generated by its bot.
We have added to several of our projects and appreciate it.
> Add codecov configuration.

- docs/source/preliminaries.rst
Was having trouble figuring out how to generate the template, so pulled `cookiecutter https://github.com/NSLS-II/scientific-python-cookiecutter` out of the prompt block into its own instruction.
> DOC: Split out the cookiecutter command

- cookiecutter.json
- {{ cookiecutter.repo_name }}/.coveragerc
This makes the coverage report much more readable and succinct by only measuring coverage of the package whose CI is being run, not every installed package.
This PR also fixes a typo in ``cookiecutter.json``.
> Add .coveragerc.

- {{ cookiecutter.repo_name }}/README.rst
This PR provides a fix for the long project names to be properly rendered in the generated `README.rst` files.
```bash
19:18 $ cookiecutter .
full_name [Name or Organization]:
email []:
github_username []:
project_name [Your Project Name]: very-very-long-name-we-all-would-like-to-handle-properly-see-issue-number-77
package_dist_name [very-very-long-name-we-all-would-like-to-handle-properly-see-issue-number-77]:
package_dir_name [very-very-long-name-we-all-would-like-to-handle-properly-see-issue-number-77]:
repo_name [very-very-long-name-we-all-would-like-to-handle-properly-see-issue-number-77]:
project_short_description [Python package for doing science.]:
year [2019]:
Select minimum_supported_python_version:
1 - 3.6
2 - 3.7
3 - 3.5
4 - 3.4
Choose from 1, 2, 3, 4 (1, 2, 3, 4) [1]:
19:18 $ …
```
> Match section separator's and project name's lengths

- docs/source/publishing-docs.rst
Reason: https://github.com/drdoctr/doctr/blob/0f19ff78c8239efcc98d417f36b0a31d9be01ba5/doctr/travis.py#L593
It's very hard to find in Travis log. Think need to mention in instruction.
> DOC: update doctr instruction

- docs/source/writing-docs.rst
Closes #71
Touches on #36 also
> Illustrate literal-include and mention sphinx-gallery.

- {{ cookiecutter.repo_name }}/LICENSE
Closes #42. 
Follow-up on #46.
The templated LICENSE file, which is then shipped with projects generated using the cookiecutter, still has a couple of references to BNL/BSA. Other details and formatting are also not quite consistent with the standard BSD 3-Clause license.
This PR removes all remaining BNL references, and brings the file in line with the "standard" as per:
https://choosealicense.com/licenses/bsd-3-clause/
The resulting LICENSE is recognized by GitHub as a standard BSD 3-Clause license.
> Fix remaining inconsistencies in templated LICENSE file

- {{ cookiecutter.repo_name }}/.travis.yml
This seems to help avoid many potentially-confusing issues, most recently
the one with imagecodecs.
> Upgrade pip and numpy from Travis defaults.

- docs/source/preliminaries.rst
At some point we updated the minimum Python versions but did not update
the walkthrough, which shows the expected cookiecutter output, to match.
Also, I think it makes sense to update our recommendation about minimum
Python versions.
> Update walkthrough to match cookiecutter.

- docs/source/publishing-releases.rst
This is a step I sometimes forget at first. Seems worth adding to the instructions.
> Add reminder to restore editable installation after git cleaning.

- docs/source/guiding-design-principles.rst
- {{ cookiecutter.repo_name }}/requirements-dev.txt
`twine` is pretty useful when installed with the rest of the development requirements.
> Update docs and development requirements

- docs/source/publishing-releases.rst
A month and a half-delayed follow-up on https://github.com/NSLS-II/scientific-python-cookiecutter/pull/87#issuecomment-820502818.
> DOC: remove `twine` manual installation step

- .gitignore
- docs/source/example_pre-commit.yaml
- docs/source/index.rst
- docs/source/pre-commit.rst
- {{ cookiecutter.repo_name }}/.pre-commit-config.yaml
- {{ cookiecutter.repo_name }}/pyproject.toml
- {{ cookiecutter.repo_name }}/requirements-dev.txt
Added pre-commit  to build git hooks. This is mostly for formatting, some of which is already taken care of in Travis-CI. However, it is convenient to have this on the client side so there are no commits in a PR just for removing jupyter notebook output or applying black. 
I started using this on the xca project for black, and added the nbstripout from [the adaptive tutorial](https://github.com/bluesky/tutorial-adaptive-RL-sampling) assuming tutorials for any library will be necessary in time. 
Very open to suggestions/criticisms here.
> Pre commit

- {{ cookiecutter.repo_name }}/.flake8
- {{ cookiecutter.repo_name }}/pyproject.toml
Configuration for `black` tool: set maximum line length to 115 characters (same line length is used in `flake8` configuration). The default line length 88 characters is not practical for most cases. The line length can be manually reduced for particular projects is needed, since it is much easier to reformat the code to make lines shorter than fix the code that was accidentally formatted with short lines (there is no automated way to reverse changes).
Configuration for `flake8` was changed to ignore some style issues produced by `black`. Those issues are unavoidable in the formatted code and should be ignored by `flake8` if it is used along with `black`. For example, `flake8` requires that the slices are specified as `[2: 5]` (no space before `:`), while `black` formats slices as `[2 : …
> Black: set maximum line length to 115 characters

- {{ cookiecutter.repo_name }}/versioneer.py
SafeConfigParser has been deprecated since Python 3.2 and will
be removed in py311.
https://github.com/python/cpython/pull/28292
https://bugs.python.org/issue45173
> Fix versioneer compat with py311

- docs/source/conf.py
- {{ cookiecutter.repo_name }}/docs/source/conf.py
This is the default behavior of Sphinx anyways, but it raises a warning to let the user know that it is subbing in `en` for `None` in the language field. These warnings cause GH Actions to fail, as seen here:
https://github.com/NSLS-II/scientific-python-cookiecutter/runs/6996988582?check_suite_focus=true
> Defaulting documentation to compile with English as language

- {{ cookiecutter.repo_name }}/.flake8
Putting a comment (starting with #) in the line with the list of `ignore` errors causes `flake8` v6.0.0 to crash. Move the comment to a separate line.
> Make .flake8 compatible with flake8 v6.0.0
